mysite/blog/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('', views.PostList.as_view(), name='home'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from register import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("register/", views.LoginView.register, name="register"),
    path("login/", views.LoginView.get, name="login"),
    path('', include('blog.urls')),
    path('', include("django.contrib.auth.urls")),

]

mysite/blog/models.py
from django.db import models
from django.contrib.auth.models import User


STATUS = (
    (0, "Draft"),
    (1, "Publish")
)


class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

mysite/register/models.py
from django.db import models


class Users(models.Model):
    email = models.EmailField(max_length=50)
    username = models.CharField(max_length=30)

    def __str__(self):
        return self.username

mysite/register/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class UserForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'type': 'username',
            'placeholder': ('Username')
        }
    ))

    email = forms.EmailField(widget=forms.TextInput(
        attrs={
            'type': 'email',
            'placeholder': ('Email')
        }
    ))
    password1 = forms.CharField(max_length=16, widget=forms.PasswordInput(
        attrs={
            # 'class':'form-control',
            'placeholder': 'Password'
        }
    ))
    password2 = forms.CharField(max_length=16, widget=forms.PasswordInput(
        attrs={
            # 'class':'form-control',
            'placeholder': 'Repeat Password'
        }
    ))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

mysite/blog/views.py
from django.views import generic
from .models import Post


class PostList(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    template_name = 'index.html'


class PostDetail(generic.DetailView):
    model = Post
    template_name = 'post_detail.html'

mysite/register/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import RegisterForm
from django.views import View
from .forms import UserForm


class LoginView(View):

    def get(request):
        form = UserForm()
        if "sign-in" in request.GET:
            username = request.GET.get("username")
            password = request.GET.get("pswd")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('/')
            else:
                messages.info(request, 'Login attemp failed.')
                return redirect('registration/login.html')
        return render(request, 'registration/login.html', {'form': form})

    def register(response,):
        if response.method == "POST":
            form = RegisterForm(response.POST)
            if form.is_valid():
                form.save()
                messages.success(response, "account created succefuly")
                return redirect("/")
            messages.error(response, "error")
            return render(response, "register/register.html", {"form": form})
        else:
            form = RegisterForm()
            messages.warning(response, "error")
        return render(response, "register/register.html", {"form": form})


class LogoutView(View):

    def get(self, request):
        logout(request)
        messages.success(request, 'Logged out succesfully.')
        return redirect('account_login')

mysite/blog/templates/blog/base.html
{%load static%}

<html>
    <head>
        <title>Django Central</title>
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
        <meta name="google" content="notranslate" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
            crossorigin="anonymous" />
        <link rel="stylesheet" href="{% static 'blog/base.css' %}" type="text/css">
     <link rel="stylesheet" href="{%static 'blog/index.css'%}">
    </head>

    <body >

        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'home' %}">Заголовок сайта</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>

  </button>

                <div class="collapse navbar-collapse" id="navbarResponsive">


                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="#">About</a>
                        </li>
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="#">Policy</a>
                        </li>
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="#">Contact</a>
                        </li>

                    </ul>

                </div>
     </div>

        </nav>

        {% block content %}

        {% endblock content %}

    </body>

</html>

mysite/blog/templates/blog/index.html
{% extends "base.html" %}
{%load static%}
{% block content %}

<head>
<link rel="stylesheet" href="{%static 'blog/index.css' %}">
	 <script src="{% static 'blog/index.js' %}" type="text/javascript"></script>
</head>
<html lang="en-US">

<body>
<div class="site-wrapper">
	<div class="main-overlay"></div>
	<header class="header-personal light">

		<nav class="navbar navbar-expand-lg">
			<div class="container-xl">

				<div class="collapse navbar-collapse justify-content-center centered-nav">
					<ul class="navbar-nav">
						<li class="nav-item dropdown active">
							<a class="nav-link dropdown-toggle" href="/">Home</a>

						</li>

						<li class="nav-item">
							<a class="nav-link" href="category.html">Inspiration</a>
						</li>
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" href="#">Pages</a>

						</li>
						<li class="nav-item">
							<a class="nav-link" href="contact.html">Contact</a>
						</li>
					</ul>
				</div>

			</div>
		</nav>
	</header>

    <section class="hero data-bg-image d-flex align-items-center">
        <div class="container-xl">
        </div>

        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 260">
            <path fill="#FFF" fill-opacity="1" d="M0,256L60,245.3C120,235,240,213,360,218.7C480,224,
            600,256,720,245.3C840,235,960,181,1080,176C1200,171,1320,213,1380,234.7L1440,
            256L1440,320L1380,320C1320,320,1200,320,1080,320C960,320,840,320,720,320C600,
            320,480,320,360,320C240,320,120,320,60,320L0,320Z">

            </path></svg>

    </section>
	<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->

        <div class="col-md-8 mt-3 left">
            {% for post in post_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p>
                    <p class="card-text">{{post.content|slice:":200" }}</p>
                    <a href="{% url 'post_detail' post.slug  %}" class="btn btn-primary">Read more... &rarr;</a>
                </div>
            </div>
            {% endfor %}
        </div>

    </div>
</div>


{%endblock%}

mysite/blog/templates/blog/post_detail.html
{% extends 'index.html' %} {% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1>{% block title %} {{ object.title }} {% endblock title %}</h1>
        <p class=" text-muted">{{ post.author }} | {{ post.created_on }}</p>
        <p class="card-text ">{{ object.content | safe }}</p>
      </div>
    </div>

  </div>
</div>

{% endblock content %}

mysite/register/templates/register/error.html
{%load static%}

<html>
    <head>
        <p>TRY AGAIN</p>>
    </head>
    <body>
    {% block content %}
    {% endblock content %}
    <h1>TRY again</h1>
    </body>

    </html>

mysite/register/templates/register/register.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<html lang="en">
<head>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
    <style media="screen">
      *,
*:before,
*:after{
    padding: 0;
    margin: 0;
    box-sizing: border-box;
}
body{
    background-color: #B1B3D8;
}
.background{
    width: 430px;
    height: 520px;
    position: absolute;
    transform: translate(-50%,-50%);
    left: 50%;
    top: 50%;
}
.background .shape{
    height: 200px;
    width: 200px;
    position: absolute;
    border-radius: 50%;
}
.shape:first-child{
    background: linear-gradient(
        #1845ad,
        #23a2f6
    );
    left: -80px;
    top: -80px;
}
.shape:last-child{
    background: linear-gradient(
        to right,
        #ff512f,
        #f09819
    );
    right: -30px;
    bottom: -80px;
}
form{
    height: 430px;
    width: 400px;
    background-color: rgba(255,255,255,0.13);
    position: absolute;
    transform: translate(-50%,-50%);
    top: 50%;
    left: 50%;
    border-radius: 10px;
    backdrop-filter: blur(10px);
    border: 2px solid rgba(255,255,255,0.1);
    box-shadow: 0 0 40px rgba(8,7,16,0.6);
    padding: 50px 35px;
}
form *{
    font-family: 'Poppins',sans-serif;
    color: #ffffff;
    letter-spacing: 0.5px;
    outline: none;
    border: none;
}
form h3{
    font-size: 32px;
    font-weight: 500;
    line-height: 42px;
    text-align: center;
    color:black;
}
label{
    display: block;
    margin-top: 30px;
    font-size: 16px;
    font-weight: 500;
}
input{
    display: block;
    height: 50px;
    width: 100%;
    background-color: rgba(255,255,255,0.07);
    border-radius: 3px;
    padding: 0 10px;
    margin-top: 8px;
    font-size: 14px;
    font-weight: 300;
    color: black
}
::placeholder{
    color: black;
}
button{
    margin-top: 30px;
    width: 100%;
    background-color: #ffffff;
    color: #080710;
    padding: 15px 0;
    font-size: 18px;
    font-weight: 600;
    border-radius: 5px;
    cursor: pointer;
}
    </style>
</head>
<body>
    <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
    </div>
    <form method="POST" class="form-group">
        <h3>Sign-up</h3>
	{% csrf_token %}
        <input type="text" name="username" placeholder="Username" maxlength="150" autofocus="" class="textinput textInput form-control" required="" id="id_username">
        <input type="email" name="email" placeholder="Email" class="emailinput form-control" required="" id="id_email">
        <input type="password" name="password1" placeholder="Password" autocomplete="new-password" class="textinput textInput form-control" required="" id="id_password1">
        <input type="password" name="password2" placeholder="Repeat Password" autocomplete="new-password" class="textinput textInput form-control" required="" id="id_password2">
	<button type="submit" class="btn btn-success">Register</button>
    </form>
		</div>
</body>
{% endblock %}